
import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, readFileSync } from 'fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");


const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: false,
	platform: "browser",
	plugins: [
		{
			name: "paipan-inline-plugin",
			setup(build) {
				build.onLoad({ filter: /src\\main\.ts$/ }, async (args) => {
					// 读取原始文件内容
					let contents = readFileSync(args.path, 'utf8');
					
					// 读取paipan.js并移除ES6导出语句
					let paipanContent = readFileSync("src/paipan.js", 'utf8');
					// 移除export { paipan }; 语句
					paipanContent = paipanContent.replace(/export\s*\{[^}]*\}\s*;?/g, '');
					paipanContent = paipanContent.replace(/`/g, '\\`');
					
					// 替换fetchPaipanContent函数为内联版本
					contents = contents.replace(
						/async function fetchPaipanContent\(\): Promise<void> \{[\s\S]*?\}/,
						`async function fetchPaipanContent(): Promise<void> {
							// 内联paipan.js内容到window.paipan（已移除export语句）
							const script = document.createElement('script');
							script.textContent = \`${paipanContent}\`;
							document.body.appendChild(script);
							// 等待脚本加载完成
							await new Promise(resolve => setTimeout(resolve, 50));
						}`
					);
					
					return { contents, loader: 'ts' };
				});
			},
		},
	],
});

// 构建时复制 paipan.js 到插件根目录，确保插件运行时可动态加载
copyFileSync("src/paipan.js", "paipan.js");

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
